
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 17 19:39:05 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 53;
  public static final int REL_EQUAL = 26;
  public static final int LTE = 31;
  public static final int CONST = 46;
  public static final int CHAR = 16;
  public static final int LPAREN = 39;
  public static final int CONTINUE = 9;
  public static final int INT = 15;
  public static final int MINUS = 22;
  public static final int STR_CONST = 52;
  public static final int STAR = 23;
  public static final int RPAREN = 40;
  public static final int AND = 32;
  public static final int LT = 30;
  public static final int NUMERIC_CONST = 51;
  public static final int OR = 33;
  public static final int COMMA = 37;
  public static final int BOOL = 17;
  public static final int SEMICOL = 35;
  public static final int CLASS = 12;
  public static final int INC = 19;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int IF = 7;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 34;
  public static final int TRUE = 47;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int NULL = 49;
  public static final int MOD = 25;
  public static final int IDENT = 50;
  public static final int BREAK = 10;
  public static final int VOID = 18;
  public static final int GTE = 29;
  public static final int COL = 36;
  public static final int ARROW = 45;
  public static final int FOREACH = 6;
  public static final int LBRACE = 43;
  public static final int ELSE = 8;
  public static final int LSQUARE = 41;
  public static final int REL_NOT_EQUAL = 27;
  public static final int READ = 4;
  public static final int RSQUARE = 42;
  public static final int WHILE = 5;
  public static final int RBRACE = 44;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int DEC = 20;
  public static final int FALSE = 48;
  public static final int GT = 28;
  public static final int PRINT = 3;
}

