
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 03 14:45:11 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 48;
  public static final int REL_EQUAL = 23;
  public static final int LTE = 28;
  public static final int CONST = 43;
  public static final int LPAREN = 36;
  public static final int CONTINUE = 9;
  public static final int MINUS = 19;
  public static final int STR_CONST = 47;
  public static final int STAR = 20;
  public static final int RPAREN = 37;
  public static final int AND = 29;
  public static final int LT = 27;
  public static final int NUMERIC_CONST = 46;
  public static final int OR = 30;
  public static final int COMMA = 34;
  public static final int SEMICOL = 32;
  public static final int CLASS = 12;
  public static final int INC = 16;
  public static final int DIV = 21;
  public static final int PLUS = 18;
  public static final int IF = 7;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 31;
  public static final int TRUE = 49;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int NULL = 44;
  public static final int MOD = 22;
  public static final int IDENT = 45;
  public static final int BREAK = 10;
  public static final int VOID = 15;
  public static final int GTE = 26;
  public static final int COL = 33;
  public static final int ARROW = 42;
  public static final int FOREACH = 6;
  public static final int LBRACE = 40;
  public static final int ELSE = 8;
  public static final int LSQUARE = 38;
  public static final int REL_NOT_EQUAL = 24;
  public static final int READ = 4;
  public static final int RSQUARE = 39;
  public static final int WHILE = 5;
  public static final int RBRACE = 41;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int DEC = 17;
  public static final int FALSE = 50;
  public static final int GT = 25;
  public static final int PRINT = 3;
}

